name: Test

on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
  build_various_platforms:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15, macos-15-intel]

    runs-on: ${{ matrix.os }}

    name: Test on ${{matrix.os}}

    steps:
      - name: checkout project
        uses: actions/checkout@v3
      - name: create a dummy tap
        run: |
          brew tap-new local/valgrind
          cp ./valgrind.rb "$(brew --repository)/Library/Taps/local/homebrew-valgrind/Formula/valgrind.rb"
      - name: install formula locally
        run: brew install --HEAD local/valgrind/valgrind
        env:
          # FIXME: needed for arm64 (for now)
          HOMEBREW_I_ACKNOWLEDGE_THIS_MIGHT_CRASH_OR_DAMAGE_MY_COMPUTER: yes
      - name: upgrade formula locally
        run: brew upgrade --fetch-HEAD local/valgrind/valgrind
